#!/bin/bash

AWS_ACCESS_KEY="AKIA123456789-EXEMPLE"
AWS_SECRET_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCY-EXEMPLE"
REGION="eu-west-3"
BUCKET_NAME="tp-ssh-logs-aurelien-leloup"
TOKEN="123456-SECRET-TOKEN"

export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
export AWS_DEFAULT_REGION=$REGION

aws s3 mb s3://$BUCKET_NAME
aws s3api put-bucket-acl --bucket $BUCKET_NAME --acl public-read
